version: "3.7"

services:
  orgs-db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=orgs
      - POSTGRES_PASSWORD=orgs
      - POSTGRES_DB=orgs-db
      - PGDATA=/pgdata
    ports:
      - "15432:5432"
    volumes:
      - link-data:/pgdata

volumes:
  orgs-data:
