version: "3.7"

services:
  link-db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=link
      - POSTGRES_PASSWORD=link
      - POSTGRES_DB=link-db
      - PGDATA=/pgdata
    ports:
      - "15432:5432"
    volumes:
      - link-data:/pgdata

volumes:
  link-data:
